# Numpy

now we can create a array using numpy like this but before that you have to import the numpy module 


In [2]:
4+6

10

In [1]:
print("hello ")

hello 


In [2]:
import numpy as np


In [6]:
import numpy as np
num1 = [2,3,34,4,5,6,6,7,7,8,8]

In [4]:
np.array([5,6,7,7,8,8,8,8,8,8,8,8,])

array([5, 6, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8])

In [7]:
np.arange(0,len(num1))


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [25]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### now above will fill out the the given 3X3 matrix with 0 or 1 depending 


In [23]:
np.ones((3,5)) 

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### now this line space will divide the segements into given 3rd argument and then it will create a array of that 

In [27]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

### now this will create a identy matrix with 5X5

In [26]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### how to create a array of random numbers 


In [33]:
np.random.rand(5,5)

array([[0.63829177, 0.28881719, 0.35754608, 0.07264903, 0.92353899],
       [0.19102694, 0.25315049, 0.2165532 , 0.68172405, 0.85782806],
       [0.47236362, 0.70816658, 0.23141871, 0.7848138 , 0.88747836],
       [0.94100285, 0.13962896, 0.52318341, 0.33541508, 0.06817737],
       [0.13742735, 0.21456587, 0.22053621, 0.61083126, 0.37012902]])

### this will also include negative values in the array 


In [41]:
arr1=np.random.randn(4,4)
arr1

array([[-0.43744665, -0.939934  , -1.79093491, -0.03419061],
       [-0.67862529, -0.63361667, -0.89663761, -2.40798361],
       [ 0.92855938,  1.91398855,  0.49333894,  1.04763909],
       [ 0.19255349, -1.18319635, -0.04802389,  0.4370532 ]])

### this will create a array having range from 1 to 100 and creating 10 random values as a array 


In [43]:
array2=np.random.randint(1,100,10)
array2

array([ 9, 42,  1,  6, 69, 11, 51, 43, 65,  4])

In [44]:
array2.reshape(2,5)

array([[ 9, 42,  1,  6, 69],
       [11, 51, 43, 65,  4]])

### max and min value with argmin and argmax 

In [45]:
array2.max()

69

In [46]:
array2.min()

1

In [47]:
array2.argmax()

4

In [48]:
array2.argmin()

2

In [49]:
array2.shape

(10,)

In [50]:
array2 = array2.reshape(2,5)

In [51]:
array2

array([[ 9, 42,  1,  6, 69],
       [11, 51, 43, 65,  4]])

In [52]:
array2.dtype

dtype('int64')